apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media-radar-svc-k8s.fullname" . }}
  labels:
    {{- include "media-radar-svc-k8s.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "media-radar-svc-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.auth.role }}"
        vault.hashicorp.com/secret-volume-path: "{{ .Values.vault.secretVolumePath | default "/vault/secrets" }}"
        {{- with .Values.vault.agent }}
        {{- with .limits }}
        vault.hashicorp.com/agent-limits-cpu: "{{ .cpu }}"
        vault.hashicorp.com/agent-limits-mem: "{{ .memory }}"
        {{- end }}
        {{- with .requests }}
        vault.hashicorp.com/agent-requests-cpu: "{{ .cpu }}"
        vault.hashicorp.com/agent-requests-mem: "{{ .memory }}"
        {{- end }}
        {{- end }}
        {{- range $name, $path := .Values.vault.inject.secrets }}
        vault.hashicorp.com/agent-inject-secret-{{ $name }}: "{{ $path }}"
        {{- end }}
        {{- range $name, $path := .Values.vault.inject.env }}
        vault.hashicorp.com/agent-inject-env-{{ $name }}: "{{ $path }}"
        {{- end }}
        {{- range $name, $template := .Values.vault.inject.templates }}
        vault.hashicorp.com/agent-inject-template-{{ $name }}: |
{{ $template | nindent 10 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "media-radar-svc-k8s.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "media-radar-svc-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.vault.enabled .Values.volumeMounts }}
          volumeMounts:
            {{- if and .Values.vault.enabled (.Values.vault.addVolumeMount | default true) }}
            - name: {{ .Values.vault.volumeName | default "vault-secrets" }}
              mountPath: {{ .Values.vault.secretVolumePath | default "/vault/secrets" | quote }}
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.vault.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      {{- if or .Values.vault.enabled .Values.volumes }}
      volumes:
        {{- if and .Values.vault.enabled (.Values.vault.addVolume | default true) }}
        - name: {{ .Values.vault.volumeName | default "vault-secrets" }}
          emptyDir:
            medium: Memory
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
